services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_STORAGE}:/var/lib/postgresql/data
    env_file:
      - .env

  django-backend:
    image: budget-assistant-backend
    build:
      dockerfile: Dockerfile-django
    container_name: django-docker
    ports:
      - "8080:8080"
      - "29781:29781"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      #DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DEBUG_PYCHARM: 'false'
      TRUNCATE_TABLES: ${TRUNCATE_TABLES:-false}
    env_file:
      - .env
volumes:
  postgres_storage:
