name: budget-assistant-backend-django
dependencies:
  - python==3.11.10
  - pip:
    - Django==5.1.2
    - djangorestframework==3.15.2
    - importlib-resources==6.4.5
    #- djangorestframework-camel-case==1.4.2
    - networkx==3.4.1
    - pandas==2.2.3
    - numpy==2.1.2
    - pydantic==2.9.2
    - arrow==1.3.0
    - djangorestframework-simplejwt==5.3.1
    - django-cors-headers==4.6.0
    - django-pandas==0.6.7
    - django-environ==0.11.2
    - drf-spectacular==0.28.0
    - django-choice-enumfields==1.1.3
    - mysqlclient==2.2.4
    - jsonpickle==4.0.1
    - whitenoise==6.9.0


