# Generated by Django 5.1.2 on 2025-04-14 16:10

import django.contrib.auth.validators
import enumfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=enumfields.fields.CharEnumField(enum={'base': 'enumfields.enums.ChoicesEnum', 'choices': {'BOTH': {'initial': True, 'value': 'BOTH'}, 'EXPENSES': {'initial': True, 'value': 'EXPENSES'}, 'REVENUE': {'initial': True, 'value': 'REVENUE'}}, 'name': 'TransactionTypeEnum', 'type': str}, max_length=10),
        ),
        migrations.AlterField(
            model_name='categorytree',
            name='type',
            field=enumfields.fields.CharEnumField(enum={'base': 'enumfields.enums.ChoicesEnum', 'choices': {'BOTH': {'initial': True, 'value': 'BOTH'}, 'EXPENSES': {'initial': True, 'value': 'EXPENSES'}, 'REVENUE': {'initial': True, 'value': 'REVENUE'}}, 'name': 'TransactionTypeEnum', 'type': str}, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
