"""Initial migration - create all tables

Revision ID: fa9439f92ead
Revises: 
Create Date: 2026-01-18 23:24:17.797823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa9439f92ead'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankaccount',
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('account_number')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('qualified_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('budgettreenode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['budgettreenode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorytree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_id')
    )
    op.create_table('counterparty',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street_and_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip_code_and_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('rulesetwrapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_set_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('user_bank_account_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_number'], ['bankaccount.account_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bank_account_number')
    )
    op.create_table('budgettree',
    sa.Column('bank_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number_of_descendants', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bankaccount.account_number'], ),
    sa.ForeignKeyConstraint(['root_id'], ['budgettreenode.id'], ),
    sa.PrimaryKeyConstraint('bank_account_id'),
    sa.UniqueConstraint('root_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('statement_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('bic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('communications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manually_assigned_category', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_advance_shared_account', sa.Boolean(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_manually_reviewed', sa.Boolean(), nullable=False),
    sa.Column('bank_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counterparty_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bankaccount.account_number'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.name'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_number')
    )
    op.create_table('user_counterparty_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_name'], ['counterparty.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'counterparty_name')
    )
    op.create_table('user_ruleset_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesetwrapper.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ruleset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ruleset_link')
    op.drop_table('user_counterparty_link')
    op.drop_table('transaction')
    op.drop_table('budgettree')
    op.drop_table('user_bank_account_link')
    op.drop_table('rulesetwrapper')
    op.drop_table('counterparty')
    op.drop_table('categorytree')
    op.drop_table('budgettreenode')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('bankaccount')
    # ### end Alembic commands ###
