name: BudgetAssistant-build-openapi-client

on:
  push:
    paths:
      - 'BudgetAssistant-backend/**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BudgetAssistant-backend
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Install pip dependencies
        run: |
          conda install -c conda-forge gcc=12
          conda run -n base pip install -r requirements-dev.txt

      - name: Generate OpenAPI schema
        run: |
          ./manage.py spectacular --color --file schema.yml
      - name: Generate OpenAPI Angular/Typescript client
        run: |
          openapi-generator-cli generate -i schema.yml -g typescript-angular -o ./api --additional-properties=modelPropertyNaming=camelCase,fileNaming=kebab-case,enumPropertyNaming=original,ngVersion=14.2.8,npmName=budget-assistant-client