name: BudgetAssistant-backend-unittests

on:
  push:
    paths:
      - 'BudgetAssistant-backend/**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BudgetAssistant-backend
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3      
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Install pip dependencies
      run: |
        conda run -n base pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pip install 
        conda install pytest
        pytest 
