name: BudgetAssistant-build-openapi-client

on:
  push:
    paths:
      - 'BudgetAssistant-backend/**'
      - '.github/workflows/BudgetAssistant-build-openapi-client.yaml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BudgetAssistant-backend
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Install pip dependencies
        run: |
          conda install -c conda-forge gcc=12
          conda run -n base pip install -r requirements-dev.txt
      - name: Make manage.py executable
        run: chmod +x ./manage.py
      - name: Set Django Allowed Hosts
        run: echo "DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,github-actions" >> $GITHUB_ENV
      - name: Generate OpenAPI schema
        env:
          DJANGO_SETTINGS_MODULE: pybackend.settings
          DATABASE_BACKEND: mysql
          EMAIL_HOST_PASSWORD: fake_password
          TEST_MODE: true
        run: |
          ./manage.py spectacular --color --file schema.yml
      - name: Generate OpenAPI Angular/Typescript client
        run: |
          openapi-generator-cli generate -i schema.yml -g typescript-angular -o ./api --additional-properties=modelPropertyNaming=camelCase,fileNaming=kebab-case,enumPropertyNaming=original,ngVersion=14.2.8,npmName=budget-assistant-client

#      - name: Install dependencies
#        run: |
#          npm install
#          npm install @types/node@latest
      - name: Update package.json for npm
        run: |
          cd ./api
          npm init -y
          npm install
          
          # Authenticate to avoid permission issues
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
          
          # Fetch existing versions, ensuring an empty array does not break jq
          VERSIONS=$(npm view @daanvdn/budget-assistant-client versions --json --registry=https://npm.pkg.github.com || echo "[]")
          echo "Existing versions: $VERSIONS"
          
          # Find the most recent version
          LATEST_VERSION=$(echo "$VERSIONS" | jq -r 'sort_by(.) | last')
          echo "Latest version: $LATEST_VERSION"
          
          # Increment the minor version number by 1
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
          NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          echo "New version: $NEW_VERSION"
          
          jq --arg version "$NEW_VERSION" \
             '.name="@daanvdn/budget-assistant-client" | .version=$version | .main="index.js" | .types="index.d.ts" | .files=["**/*"] | .publishConfig={"@daanvdn:registry":"https://npm.pkg.github.com"}' package.json > package.tmp.json
          jq 'walk(if type == "string" then gsub("GIT_USER_ID"; "daanvdn") else . end)' package.tmp.json > package.tmp.json2
          jq 'walk(if type == "string" then gsub("GIT_REPO_ID"; "BudgetAssistant") else . end)' package.tmp.json2 > package.tmp.json3
          mv package.tmp.json3 package.json
          
          # Store full package name in environment variable
          echo "PACKAGE_NAME=budget-assistant-client-$NEW_VERSION.tgz" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Package npm module
        run: |
          cd ./api
          npm pack
      - name: Print all files in the current directory
        run: |
          echo "Files in the current directory:"
          ls -al
          echo "Files in the api directory:"
          ls -al ./api
      - name: Upload npm package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ./BudgetAssistant-backend/api/${{ env.PACKAGE_NAME }}
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
      - name: Publish npm package to GitHub Packages
        run: |
          cd ./api
          npm publish --access public --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}